apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: crossmap
    component: api
resources:
- deployment.yml
- service.yml
configMapGenerator:
- name: crossmap-api
secretGenerator:
- name: crossmap-api
images:
- name: images.home.mtaylor.io/crossmap-api
  newTag: 0.0.8
