apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: images.home.mtaylor.io/crossmap-dev-api
  newTag: develop
labels:
- includeSelectors: true
  pairs:
    app: crossmap-dev
    component: api
resources:
- deployment.yml
- service.yml
configMapGenerator:
- name: crossmap-dev-api
secretGenerator:
- name: crossmap-dev-api
