name: Build Image
on:
  workflow_dispatch:
jobs:
  build-image:
    name: Docker Build Image
    runs-on: crossmap-dev-runners-dind
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout
        uses: actions/checkout@v4
      - id: meta
        name: Docker Metadata
        uses: docker/metadata-action@v5
        with:
          images: images.home.mtaylor.io/crossmap-dev-api-build
          tags: |
            latest
            type=sha
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile.build
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
