name: Continuous Deployment
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
jobs:
  git-tag:
    name: Git Tag
    runs-on: crossmap-dev-runners-k8s
    container:
      image: images.home.mtaylor.io/deployer:0.0.9
    steps:
    - uses: actions/checkout@v4
    - name: "Configure git"
      shell: "bash"
      run: |
        git config --global user.email "githubactions@crossmap.dev"
        git config --global user.name "GitHub Actions"
        git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Git Tag
      shell: bash
      run: git tag -a ${{ inputs.tag }} -m "Release ${{ inputs.tag }}"
    - name: Git Push
      shell: bash
      run: git push origin ${{ inputs.tag }}
