name: Continuous Integration
on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: true
jobs:
  haskell-build:
    name: Haskell Build
    runs-on: crossmap-dev-runners-k8s
    container:
      image: images.home.mtaylor.io/crossmap-dev-api-build:sha-4f2c0f3
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/haskell-build
  docker-image:
    name: Docker Image
    needs: haskell-build
    runs-on: crossmap-dev-runners-dind
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/docker-image
      with:
        tags: ${{ inputs.tags }}
