name: Development Branch CI
on:
  push:
    branches: [develop]

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sha:
    name: Read SHA
    runs-on: crossmap-dev-runners-k8s
    container:
      image: docker.io/debian:bookworm-slim
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
    steps:
    - id: sha
      name: Compute SHA
      shell: bash
      run: echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
  ci:
    name: Continuous Integration
    needs: [sha]
    uses: ./.github/workflows/ci.yml
    with:
      tag: sha-${{ needs.sha.outputs.sha }}
      tags: |
        develop
        type=sha
  cd:
    name: Continuous Deployment
    needs: [ci]
    uses: ./.github/workflows/cd.yml
    with:
      env: dev
    secrets: inherit
