name: Development Branch CI
on:
  push:
    branches: [develop]

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml
    with:
      tags: |
        develop
        type=sha
