name: Main Branch CI
on:
  push:
    branches: [main]

# INFO: The following configuration block ensures that only one build runs per branch,
# which may be desirable for projects with a costly build process.
# Remove this block from the CI workflow to let each CI job run to completion.
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Read Version
    runs-on: crossmap-dev-runners-k8s
    container:
      image: docker.io/debian:bookworm-slim
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    - id: version
      name: Read version
      shell: bash
      run: echo "version=$(tr -d '\n' < VERSION.txt)" >> $GITHUB_OUTPUT
  ci:
    name: Continuous Integration
    needs: [version]
    uses: ./.github/workflows/ci.yml
    with:
      tags: |
        latest
        ${{ needs.version.outputs.version }}
        type=sha
  cd:
    name: Continuous Deployment
    needs: [ci, version]
    uses: ./.github/workflows/cd.yml
    with:
      env: prod
      tag: ${{ needs.version.outputs.version }}
