name: Promote Development Branch
on:
  workflow_dispatch:
jobs:
  promote:
    name: Promote Development Branch
    runs-on: crossmap-dev-runners-k8s
    container:
      image: images.home.mtaylor.io/deployer:0.0.9
    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
    - name: Configure git
      shell: bash
      run: |
        git config --global user.email "githubactions@crossmap.dev"
        git config --global user.name "GitHub Actions"
        git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Promote
      shell: bash
      run: bin/promote.sh
